export enum DataBaseCustomNames {
  Users = 'users',
  UserTokens = 'userTokens',
  UserLogin = 'userLogins',
  Roles = 'roles',
  Settings = 'settings',
  ApplicationInfo = 'applicationInfo',
  DomainHosts = 'domainHosts',
  MigrationDbs = 'migrationDbs',
  FileUploads = 'fileUploads',
  Languages = 'languages',
  Translations = 'translations',
  Menus = 'menus',
  Permissions = 'permissions',
  PermissionActions = 'permissionActions',
}
