export enum ErrorEnum {
  Login_Invalid = 1000,
  Login_Inactive = 1100,
  Invalid_Token = 1200,
  User_Not_Found = 1300,
  Duplicate_Record = 1400,
  Password_Not_Match = 1500,
  UnAuthorized = 1600,
  Token_Expired = 1700,
  UnAuthorized_Access = 1800,
  Api_Rate_Limit = 1900,
  Error_Upload_Files = 2000,
  Error_Update = 2100,
  Error_Create = 2200,
  Error_Delete = 2300,
  Upload_File_Error = 2400,
  Bad_Request = 400,
  Not_Found = 404,
}

export const ErrorMessageMapping = new Map<ErrorEnum, string>([
  [ErrorEnum.Login_Invalid, 'Username or Password is invalid'],
  [ErrorEnum.Login_Inactive, 'Username is inactive'],
  [ErrorEnum.Duplicate_Record, 'Duplicate record'],
  [ErrorEnum.Invalid_Token, 'Invalid Token'],
  [ErrorEnum.User_Not_Found, 'User not found!'],
  [ErrorEnum.Password_Not_Match, 'Password not match!'],
  [ErrorEnum.UnAuthorized, 'Authorized Required!'],
  [ErrorEnum.Token_Expired, 'Token expired or invalid.'],
  [ErrorEnum.UnAuthorized_Access, 'Unauthorized Access'],
  [ErrorEnum.Api_Rate_Limit, 'Too many requests, please try again later.'],
  [ErrorEnum.Error_Upload_Files, 'Error to upload files'],
  [ErrorEnum.Error_Create, 'Created failed!'],
  [ErrorEnum.Error_Update, 'Updated failed!'],
  [ErrorEnum.Error_Delete, 'Deleted failed!'],
  [ErrorEnum.Not_Found, 'Not Found!'],
  [ErrorEnum.Upload_File_Error, 'Upload File Error!'],
]);
